### ISSUE TITLE
How it will use in Android Kotlin?

### ISSUE THREAD

**Issue by ankurbhut** [jaydenseric/graphql-multipart-request-spec#35]
I need to Upload one image in CreateUser Mutation. So how it possible to do that?

**Comment by dmitry** [comment]
@ankurbhut probably that's what you are looking for: https://github.com/apollographql/apollo-android

**Comment by ankurbhut** [comment]
@dmitry I have seen that But didn't got any proper function or example for file upload. If you have knowledge of that then please help me.

**Comment by jaydenseric** [comment]
Other people feel free to answer the question raised in this issue; closing because it’s not something actionable about the spec itself.

**Comment by ankurbhut** [comment]
If you closed this issue then how other people can answer on it?

**Comment by jaydenseric** [comment]
> how other people can answer on it?

@ankurbhut not following what you mean by that. This issue is not locked — you just made a comment, so other people can answer with comments.

A reminder that [at least 16 people](https://github.com/jaydenseric/graphql-multipart-request-spec/watchers) are notified via email every time someone makes a comment in this repo, and they are really only interested in actual spec bugs or changes. GitHub issues is not the best place for general conversation or advice.

**Comment by dmitry** [comment]
@ankurbhut in the github repo I gave you there are a readme, in readme you could find a tutorial for the kotlin: https://www.apollographql.com/docs/android/essentials/get-started-kotlin/
