### ISSUE TITLE
Some missing points

### ISSUE THREAD

**Issue by mcg-web** [jaydenseric/graphql-multipart-request-spec#9]
Hi,
We are implementing a middleway to this [php lib](https://github.com/overblog/GraphQLBundle/pull/288) for some backward compatibility reasons we can't use php middleway lib... but It seems specifications don't explains:
* how server deal with optional files? Can you provide an example of request payload and server behavior in this case?
* how server answer in case of batch request?

Can you please help me to get all this?

**Comment by jaydenseric** [comment]
Sorry for the late response, I need to stop clearing notifications right after I wake up!

> how server answer in case of batch request?

This is outside the domain of this spec, but the answer is exactly the same as [a regular batched request](https://www.apollographql.com/docs/apollo-server/requests.html#batching): The response will be an array of GraphQL responses.

> how server deal with optional files?

Not really sure what you mean. If there are no files in the operation to upload, then send a regular POST request instead of a multipart request. If there are two optional file arguments/variables and only one is populated, the genuinely `null` one will not have an entry in the `map` field and no file field will be appended for it.

**Comment by mcg-web** [comment]
Thanks , that's exactly what was missing me 👍
